INSERT INTO ACTIVITIES(ID, ACTIVITYNAME, COMPLETED, ACTIVITYDATE) VALUES(1, 'Read Spring Boot CLI', 'Y', current_date());
INSERT INTO ACTIVITIES(ID, ACTIVITYNAME, COMPLETED, ACTIVITYDATE) VALUES(2, 'Develop Spring Boot Kotlin App', 'N', current_date()-3);
INSERT INTO ACTIVITIES(ID, ACTIVITYNAME, COMPLETED, ACTIVITYDATE) VALUES(3, 'Deploy Spring Boot App to Heroku', 'N', current_date() + 3);